#define BAR_WATERTEMP1_XPOS 30
#define BAR_WATERTEMP1_YPOS 30
#define BAR_WATERTEMP1_SIZEX 200
#define BAR_WATERTEMP1_SIZEY 20

#define BAR_WATERTEMP2_XPOS 30
#define BAR_WATERTEMP2_YPOS 70
#define BAR_WATERTEMP2_SIZEX 20
#define BAR_WATERTEMP2_SIZEY 200/*  */


void bar_waterTemp1(void);
