#define BAR_WATERTEMP1_XPOS 30
#define BAR_WATERTEMP1_YPOS 30
#define BAR_WATERTEMP1_SIZEX 250
#define BAR_WATERTEMP1_SIZEY 30

#define BAR_WATERTEMP2_XPOS 30
#define BAR_WATERTEMP2_YPOS 100
#define BAR_WATERTEMP2_SIZEX 250
#define BAR_WATERTEMP2_SIZEY 30/*  */


void bar_waterTemp1(void);
void bar_waterTemp2(void);
